/*******************************************************************************
 * MIT License
 *
 * Copyright 2023 DSDMS
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE
 ******************************************************************************/

package dsdms.dossier.model.entities

import dsdms.dossier.model.valueObjects.ExamsStatus
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * Represents a complete Dossier.
 * @param name: name of subscriber
 * @param surname: surname of subscriber
 * @param birthdate: birthdate of subscriber to verify that he has the minimum age
 * @param fiscal_code: of subscriber for additional info
 * @param validity: representing validity of the dossier (true by default)
 * @param examsStatus: representing practical and theoretical exams global states
 * @param _id: autogenerated identifier of dossier
 */
@Serializable
data class Dossier(
    val name: String,
    val surname: String,
    val birthdate: String,
    val fiscal_code: String,
    @Contextual val _id: String? = null,
    val validity: Boolean = true,
    val examsStatus: ExamsStatus = ExamsStatus(),
)
